config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :news

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
 }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
root "news#index"

end

app/models/news.rb
class News < ApplicationRecord
    has_many :comments, dependent: :destroy
    accepts_nested_attributes_for :comments, allow_destroy: true
    belongs_to :user
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ show edit update destroy create ]
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:id, :nombre, :telefono ])
    devise_parameter_sanitizer.permit(:account_update, keys: [:id, :nombre, :telefono])
end


  # GET /news or /news.json
  def index
    @news = News.all
  end

  # GET /news/1 or /news/1.json
  def show
    @news = News.find(params[:id])
    @comments = Comment.where(news_id: @news.id)
    @comment = @news.comments.build
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_url(@news), notice: "News was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_url(@news), notice: "News was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:id, :title, :body, :user, :comment_id,)
    end
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:title, :body, :user,])
    end

    

end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news) do |form| %>
  <% if news.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="mb-3">
    <%= form.label :Noticia, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div class="mb-3">
    <%= form.label :usuario, style: "display: block" %>
    <%= form.text_field :user %>
  </div>

  <div class="mt-3 ">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/news/_news.html.erb
<div id="<%= dom_id news %>">
  <p>
    <strong>Titular</strong>
    <%= news.title %>
  </p>

  <p>
    <strong> Noticia </strong>
    <%= news.body %>
  </p>

  <p>
    <strong> creado por:</strong>
    <%= news.user%>
  </p>

</div>

<div id="<%= dom_id pet %>" class="col-4">

=begin
<div class="card">
<%pet.images.each do |imagen|%>
  <%= image_tag imagen, class: 'card-img-top' %>
  <%end%>
  <div class="card-body">
    <h5 class="card-title"><%= pet.name %></h5>
    <p class="card-text">
    <strong>Name:</strong><%= pet.name %><br>
    <strong>Race:</strong><%= pet.race %><br>
    <strong>Age:</strong><%= pet.age %><br>
    <strong>Gender:</strong><%= pet.gender %><br>
    <strong>Item:</strong><%= pet.item %><br>
    <strong>User:</strong><%= pet.user.nombre %><br>
    </p>
    <%= link_to "Show this pet", pet ,class:"btn btn-primary"%>
  </div>
</div>
=end

app/views/news/edit.html.erb
<h1 class= "text-center">Editar Noticia</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Mostar noticia", @news %> |
  <%= link_to "Regresar", news_index_path %>
</div>

app/views/news/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class= "text-center">Noticias</h1>

<div id="news">
  <% @news.each do |news| %>
    <%= render news %>
    <p>
      <%= link_to "Mostrar Noticia", news %>
    </p>
  <% end %>
</div>

<%= link_to "Nueva Noticia", new_news_path, class: "btn btn-primary" %>

<p style="color: green"><%= notice %></p>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Back to news", news_index_path, class: "btn btn-primary"%>
</div>

app/views/news/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @news %>

<div>
  <%= link_to "Edit this news", edit_news_path(@news) %> |
  <%= link_to "Back to news", news_index_path %>

  <%= button_to "Destroy this news", @news, method: :delete %>
</div>